### ISSUE TITLE
项目怎么用，可以加个微信不

### ISSUE THREAD

**Issue by Zhang-haohua** [Maryin-c/KeywordSpider_pictures_videos#1]
我的微信z1106450575

**Comment by Maryin-c** [comment]
> 我的微信z1106450575

程序直接运行main.py，关键词在excel里改，其他设置在settings.py里改，按README.md里的教程使用。

**Comment by Zhang-haohua** [comment]
> > 我的微信z1106450575
> 
> 程序直接运行main.py，关键词在excel里改，其他设置在settings.py里改，按README.md里的教程使用。

昨天运行成功啦，关键词也会设置了，其实我想爬取知乎所有含择偶，脱单，找对象的问题，然后在那些问题下搜索含关键词（可以空格分开，多关键词搜索）的所有回答（回答数只看最近一年的）哈哈哈

**Comment by Zhang-haohua** [comment]
老实人被催婚催急了，但老乡不好找，老哥的这个还不能满足，扎心，我得琢磨琢磨了，昨天不会运行是因为不会py哈哈
