### ISSUE TITLE
咨询一下

### ISSUE THREAD

**Issue by TreeGrow** [Maryin-c/KeywordSpider_pictures_videos#2]
模拟鼠标滑动，可以修改成js注入模拟滑动吗，这样就可以实现无头运行吧。

**Comment by Maryin-c** [comment]
> 模拟鼠标滑动，可以修改成js注入模拟滑动吗，这样就可以实现无头运行吧。

我自己在爬知乎的时候用js注入被反爬了，所以改的鼠标模拟，其他的没试过直接全部这么写了，你可以试试，说不定每个人遇到的情况会不一样
